<?php
// $Id$
/* Copyright (C) 2011  Jeff Lyon, NYC Public Advocate, <jeff@albatrossdigital.com>
 * 
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>
 */
 
include_once('landlord_watchlist_dashboard.features.inc');


/**
 * Implementatation of hook_menu().
 */
function landlord_watchlist_dashboard_menu() {
  $items = array();
  
  $items['admin/dashboard'] = array(
    'title' => 'Dashboard',
    'description' => 'The dashboard for site administrators.',
    'page callback' => 'landlord_watchlist_dashboard_page',
    'access arguments' => array('administer nodes'),
    'weight' => -10,
  );

  return $items;
}

/**
 * Page callback for admin/dashboard.
 */
function landlord_watchlist_dashboard_page(){
  drupal_add_css(drupal_get_path('module', 'landlord_watchlist_dashboard') .'/dashboard.css', 'module');
  drupal_add_js(drupal_get_path('module', 'landlord_watchlist_dashboard') .'/jquery.visited.js');
  drupal_add_js(drupal_get_path('module', 'landlord_watchlist_dashboard') .'/dashboard.js');  
  return t('Follow the steps in the checklist on the left to set up your Landlord Watchlist');
}
